CREATE SCHEMA IF NOT EXISTS core;
CREATE SCHEMA IF NOT EXISTS eps;
CREATE SCHEMA IF NOT EXISTS mms;
CREATE SCHEMA IF NOT EXISTS wms;
CREATE SCHEMA IF NOT EXISTS srs;
CREATE SCHEMA IF NOT EXISTS audit;
CREATE SCHEMA IF NOT EXISTS reporting;

